name: kasrzero_flutter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-263.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.4
  shared_preferences: ^2.0.15
  image_picker: ^0.8.6
  splashscreen: ^1.3.5
  font_awesome_flutter: ^10.2.1
  flutter_screenutil: ^5.6.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - images/

  # fonts:
  #   - family: Pacifico
  #     fonts:
  #       - asset: fonts/Pacifico-Regular.ttf
  #   - family: Cinzel
  #     fonts:
  #       - asset: fonts/Cinzel-Medium.ttf
  #   - family: Amiri
  #     fonts:
  #       - asset: fonts/Amiri-Regular.ttf
  #   - family: Karla
  #     fonts:
  #       - asset: fonts/Karla-Medium.ttf
